Integration user wallet reputation #100
e-Learning-DAO/POCRE pull request #115
Opened 2022-11-01 10:36 UTC by SHUJAAT-DEV

2022-11-01 15:56 UTC, huzaifa-99 commented on app/api/src/services/user.service.ts
> +  image_url?: string;
we should remove `image_url` from here

2022-11-01 16:00 UTC, huzaifa-99 commented on app/web-frontend/src/hooks/userWalletService.js
> +    if (userProfileImageUpload.code >= 400) throw new Error('Failed to fetch material');
maybe we can update this error message to `Failed to update user image` or something similar

2022-11-01 16:06 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Wallet/detail/walletDetailEdit.js
>          <Input
These `Input` fields can be wrapper with the `Form` element https://github.com/e-Learning-DAO/POCRE/blob/main/app/web-frontend/src/components/uicore/Form/index.js. The form element will add form validation and other goodies with less boilerplate. 

There is a similar implementation here
https://github.com/e-Learning-DAO/POCRE/blob/main/app/web-frontend/src/pages/Litigations/Create/Steps/One.js#L138-L322

I believe if there is no solid requirement for form validation at this screen, then this suggested change can be ignored.

2022-11-01 16:08 UTC, huzaifa-99 requested changes
.

2022-11-02 14:33 UTC, SHUJAAT-DEV commented on app/api/src/services/user.service.ts
> +  image_url?: string;
I have added image_url because we are using an image_url  in the wallet page.

2022-11-02 14:33 UTC, SHUJAAT-DEV commented on app/web-frontend/src/pages/Wallet/detail/walletDetailEdit.js
>          <Input
I have added The Form and Input  and remove the extra  code.Select field remaining same  because reusable component is not working for me .

2022-11-02 14:51 UTC, SHUJAAT-DEV commented on app/web-frontend/src/pages/Wallet/detail/walletDetailEdit.js
>          <Input
currently we don't have any validation requirement . I have added validation file also in case we need in future .

2022-11-02 20:53 UTC, huzaifa-99 commented on app/api/src/services/user.service.ts
> +  image_url?: string;
yes I understand it will be needed and you also added here https://github.com/e-Learning-DAO/POCRE/pull/115/files/f6a1d2e5b5604627256bace5cac167d275323fa5#diff-899b54e0530c478dca313660546ff85c5eb5831e1a9cc65c3eb7d8a90d630f8fR16

But also I believe we don't need `image_url?: string;` on line 44 because then it will be inside `IUserQuery` interface which may be totally irrelevant since this interface is only used to handle `GET /creations` endpoint logic as of yet

2022-11-03 02:37 UTC, SHUJAAT-DEV commented on app/api/src/services/user.service.ts
> +  image_url?: string;
removed

2022-11-03 10:14 UTC, merged