Replace zustand store with react query .
e-Learning-DAO/POCRE pull request #141
Opened 2022-11-12 13:05 UTC by shujaatcodecrafter

1. Added new routes for user wallet information.
2. replace zustand store with react query from the home page and wallet.

2022-11-12 19:59 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Home/useHome.js
> +    isLoading: isTrendingListFeched,
minor typo `isTrendingListFeched `

2022-11-12 20:00 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Home/useHome.js
> +    isLoading: isTopAuthorListFeched,
`isTrendingListFeched ` -> `isTrendingListFetched `

2022-11-12 20:00 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Home/useHome.js
> +    isLoading: isMaterialListFeched,
`isMaterialListFeched` -> `isMaterialListFetched`

2022-11-12 20:01 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Home/useHome.js
> +  });
I think this can be moved out of react query, into a const object/array

2022-11-12 20:05 UTC, huzaifa-99 commented on app/web-frontend/src/routes/index.js
> +import UserWallet from 'pages/Wallet/userWallet';
How about we rename `userWallet` page to `Dashboard` in the wallet directory?

2022-11-12 20:08 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Wallet/detail/walletDetailEdit.js
> +    updateUser(userData);
i think we should `await` here for `updateUser(userData);`

2022-11-12 20:10 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Wallet/detail/walletDetail.js
> +      fetchUserDetialById(displayOnlyId);
minor typo `fetchUserDetialById(displayOnlyId);` => `fetchUserDetailsById(displayOnlyId);`

2022-11-12 20:10 UTC, huzaifa-99 commented on app/web-frontend/src/pages/Wallet/detail/walletDetail.js
> +    uploadUserImage(file);
better to `await` hear for `uploadUserImage(file);`

2022-11-12 20:12 UTC, huzaifa-99 requested changes
.

2022-11-13 05:22 UTC, SHUJAAT-DEV commented on app/web-frontend/src/pages/Wallet/detail/walletDetail.js
> +    uploadUserImage(file);
react-query mutation  function does not return a promise, therefore it shows  **'await' has no effect on the type ...*

2022-11-13 05:32 UTC, SHUJAAT-DEV commented on app/web-frontend/src/routes/index.js
> +import UserWallet from 'pages/Wallet/userWallet';
hmm ok, will be great if we need anything else to add in the future.

2022-11-16 10:15 UTC, merged